name: R Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '31 15 * * *'  # Adjusted to run at 17:30 UTC

jobs:
  run_rscript:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies      
      run: | 
        R -e 'system("sudo apt install libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libudunits2-dev")'
        R -e 'system("sudo apt-get install libcurl4-openssl-dev")'
        R -e 'system("sudo apt-get install libharfbuzz-dev")'
        R -e 'system("sudo apt-get install libfribidi_dev")'
        R -e 'system("sudo apt-get install -y libpoppler-cpp-dev")'
        R -e 'system("sudo apt-get install harfbuzz-devel fribidi-devel")'
        R -e 'install.packages(c("emayili","gmailr","csodata","httr","gargle", "googleAuthR", "jsonlite", "knitr", "dplyr", "huxtable", "tidyverse", "rmarkdown", "csodata", "xts", "calendar", "DescTools", "splitstackshape", "pdftools", "rvest", "lubridate", "httr2","stringr","rlang","purrr","httpuv","xlsx"), repos="http://cran.rstudio.com/")'





    - name: Debug
      run: |
        ls -R
        echo "Current directory: $(pwd)"

    - name: Make script executable
      run: chmod +x .github/workflows/Rscript_analysis.r

    - name: Run R script
      run: Rscript .github/workflows/Rscript_analysis.r

    - name: Move CSV to Repository
      run: mv .github/workflows/econ_cal.csv .

    - name: Commit and Push Changes
      run: |
        git config --local user.email "mflanagan202@gmail.com"
        git config --local user.name "mflanagan201"
        git add econ_cal.csv
        git commit -m "Add econ_cal.csv"
        git push
