name: R Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 06 * * *'

jobs:
  run_rscript:
    runs-on: ubuntu-22.04

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies      
      run: | 
        sudo apt-get update
        sudo apt-get install -y libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libudunits2-dev libcurl4-openssl-dev libpoppler-cpp-dev default-jdk
        R -e 'install.packages(c("calendar","xts","knitr","jsonlite","readr","webshot2","tinytex","kableExtra","formattable","reshape2","magrittr","htmltools","htmlwidgets","formatR","waterfalls","readxl","httr","googleAuthR"))'

    - name: Install remotes package
      run: Rscript -e 'install.packages("remotes", repos = "http://cran.us.r-project.org")'

    - name: Debug
      run: |
        ls -R
        echo "Current directory: $(pwd)"

    - name: Make script executable
      run: chmod +x .github/workflows/Rscript_analysis.r

    - name: Run R script
      run: Rscript .github/workflows/Rscript_analysis.r

    - name: Commit and Push Changes
      run: |
        git config --local user.email "mflanagan202@gmail.com"
        git config --local user.name "mflanagan201"
        git add .
        git commit -m "Add econ_cal.csv"
        git push