name: R Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 06 * * *'  

jobs:
  run_rscript:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3.3.2
      key: ${{ runner.os }}-r-${{ hashFiles('R/DESCRIPTION', '.github/workflows/Rscript_analysis.r') }}
      restore-keys: ${{ runner.os }}-r-

    - name: Install dependencies
      run: |
        R -e 'install.packages(c("readr","webshot2","tinytex","kableExtra","formattable","reshape2","magrittr","htmltools","htmlwidgets","formatR","waterfalls","readxl","units","rdbnomics","openxlsx","reshape","rJava","xlsxjars","xlsx","gmailr","emayili","csodata","httr", "gargle", "googleAuthR", "jsonlite", "knitr", "dplyr", "huxtable", "tidyverse", "rmarkdown", "csodata", "xts", "calendar", "DescTools", "splitstackshape", "pdftools", "rvest", "lubridate", "httr2","stringr","rlang","purrr","httpuv","xlsx"), repos="http://cran.rstudio.com/")'

    - name: Debug
      run: |
        ls -R
        echo "Current directory: $(pwd)"

    - name: Make script executable
      run: chmod +x .github/workflows/Rscript_analysis.r

    - name: Run R script
      run: Rscript .github/workflows/Rscript_analysis.r

    - name: Commit and Push Changes
      run: |
        git config --local user.email "mflanagan202@gmail.com"
        git config --local user.name "mflanagan201"
        git add .
        git commit -m "Add econ_cal.csv"
        git push
