name: Major 

on:
  push:
    branches:
      - main
  schedule:
    - cron: '25 9 * * *'  

jobs:
  run_rscript:
    runs-on: ubuntu-22.04

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
           r-version: '4.2.2'

    - name: Install dependencies      
      run: | 
        R -e 'system("sudo apt install libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libudunits2-dev")'
        R -e 'system("sudo apt-get install libcurl4-openssl-dev")'
        R -e 'system("sudo apt-get install libharfbuzz-dev")'
        R -e 'system("sudo apt-get install libfribidi_dev")'
        R -e 'system("sudo apt-get install -y libpoppler-cpp-dev")'
        R -e 'system("sudo apt-get install harfbuzz-devel fribidi-devel")'
        R -e 'system("sudo apt-get install -y default-jre")'
        R -e 'system("sudo apt-get install -y default-jdk")'
        R -e 'system("sudo apt-get install libgdal-dev")'
        R -e 'system("sudo apt-get install r-cran-sf")'   
        R -e 'install.packages(c("timeSeries","readr","webshot2","tinytex","kableExtra","formattable","reshape2","magrittr","htmltools","htmlwidgets","formatR","waterfalls","readxl","units","rdbnomics","openxlsx","reshape","rJava","xlsxjars","xlsx","gmailr","emayili","csodata","httr", "gargle", "googleAuthR", "jsonlite", "knitr", "dplyr", "huxtable", "tidyverse", "rmarkdown", "csodata", "xts", "calendar", "DescTools", "splitstackshape", "pdftools", "rvest", "lubridate", "httr2","stringr","rlang","purrr","httpuv","xlsx","eurostat","tframe","tframePlus","webshot","eurostat","csodata"), repos="http://cran.rstudio.com/")'

    - name: Install PhantomJS
      run: Rscript -e "webshot::install_phantomjs()"

    - name: Debug
      run: |
        ls -R
        echo "Current directory: $(pwd)"

    - name: Make script executable
      run: chmod +x .github/workflows/Macro_Releases.R

    - name: Run R script
      run: Rscript .github/workflows/Macro_Releases.R


    - name: Commit and Push Changes
      run: |
       git config --local user.email "mflanagan202@gmail.com"
       git config --local user.name "mflanagan201"
       git add .
       git commit -m "Add Inflation_contributions_graph_data.XLSX, Waterfall_graph_data.XLSX, trimmed_graph_data.XLSX, MEGA_DATA_DOWNLOAD.xlsx,VOTEDSPENDING.XLSX,ct.xlsx,tax_revenue.xlsx,MONTHLY_DATA_DOWNLOAD_ALL.xlsx,QUARTERLY_DATA_DOWNLOAD_ALL.xlsx, SUMMARY_EXPORT_DATA_DOWNLOAD.xlsx and EXPORT_DATA_DOWNLOAD_ALL.xlsx"
       git pull --rebase origin main # Use rebase to avoid a merge commit
       # Resolve any conflicts that may arise during the pull
       git push
